In [1]:
import torch

In [2]:
torch.__version__

'2.6.0+cu126'

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4060'

In [9]:
## Creating a Tensor
### Empty Tensor

a = torch.empty(2,3)
a

tensor([[-4.5064e+15,  1.8161e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [10]:
type(a)

torch.Tensor

In [13]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
torch.rand(2,3)

tensor([[0.2171, 0.3983, 0.4225],
        [0.5097, 0.4314, 0.8333]])

In [50]:
torch.manual_seed(500)
torch.rand(2,3)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105]])

In [53]:
b = torch.tensor([[1,2,3], [4,5,6]])

In [54]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [55]:
type(b)

torch.Tensor

In [56]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
torch.arange(5,10)

tensor([5, 6, 7, 8, 9])

In [59]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [64]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [67]:
torch.rand(5,5)

tensor([[0.3343, 0.4265, 0.7764, 0.9990, 0.6655],
        [0.6095, 0.2643, 0.5313, 0.4334, 0.5522],
        [0.8673, 0.1170, 0.8498, 0.1451, 0.3060],
        [0.0766, 0.8693, 0.4291, 0.4616, 0.2494],
        [0.1452, 0.6103, 0.9552, 0.2300, 0.2795]])

In [68]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [70]:
torch.full((2,3),4)

tensor([[4, 4, 4],
        [4, 4, 4]])

In [71]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
b.shape

torch.Size([2, 3])

In [78]:
torch.rand(5,5)

tensor([[0.9603, 0.1389, 0.9673, 0.9375, 0.8013],
        [0.9499, 0.5046, 0.1044, 0.5435, 0.0037],
        [0.5772, 0.1708, 0.7821, 0.7593, 0.3890],
        [0.2330, 0.2108, 0.9312, 0.8975, 0.8563],
        [0.3906, 0.3622, 0.7567, 0.4265, 0.5524]])

In [81]:
torch.tensor([1.2,3.4,5.6], dtype=torch.int64)

tensor([1, 3, 5])

In [84]:
c = torch.tensor([1,2,3], dtype=torch.float32)
c

tensor([1., 2., 3.])

In [85]:
c.dtype

torch.float32

In [86]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [87]:
torch.ones_like(b)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [88]:
torch.zeros_like(b)

tensor([[0, 0, 0],
        [0, 0, 0]])

### **Mathematical Operations**

In [89]:
d = torch.rand(3,4)

In [90]:
d

tensor([[0.2083, 0.1017, 0.9709, 0.2923],
        [0.9421, 0.0926, 0.5898, 0.9607],
        [0.0080, 0.0765, 0.1419, 0.4281]])

In [91]:
### add

d + 2

tensor([[2.2083, 2.1017, 2.9709, 2.2923],
        [2.9421, 2.0926, 2.5898, 2.9607],
        [2.0080, 2.0765, 2.1419, 2.4281]])

In [92]:
d - 2

tensor([[-1.7917, -1.8983, -1.0291, -1.7077],
        [-1.0579, -1.9074, -1.4102, -1.0393],
        [-1.9920, -1.9235, -1.8581, -1.5719]])

In [93]:
d * 2

tensor([[0.4166, 0.2033, 1.9418, 0.5845],
        [1.8842, 0.1852, 1.1795, 1.9214],
        [0.0159, 0.1529, 0.2838, 0.8562]])

In [94]:
d / 4

tensor([[0.0521, 0.0254, 0.2427, 0.0731],
        [0.2355, 0.0232, 0.1474, 0.2402],
        [0.0020, 0.0191, 0.0355, 0.1070]])

In [95]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [96]:
a

tensor([[0.6209, 0.0415, 0.2424],
        [0.1610, 0.3626, 0.8453]])

In [97]:
b

tensor([[0.3928, 0.5671, 0.3231],
        [0.4891, 0.5484, 0.3335]])

In [98]:
a + b

tensor([[1.0137, 0.6085, 0.5656],
        [0.6501, 0.9110, 1.1788]])

In [99]:
a - b

tensor([[ 0.2281, -0.5256, -0.0807],
        [-0.3281, -0.1858,  0.5118]])

In [100]:
a * b

tensor([[0.2439, 0.0235, 0.0783],
        [0.0787, 0.1989, 0.2819]])

In [101]:
a / b

tensor([[1.5807, 0.0731, 0.7503],
        [0.3291, 0.6613, 2.5348]])

In [102]:
a - b

tensor([[ 0.2281, -0.5256, -0.0807],
        [-0.3281, -0.1858,  0.5118]])

In [103]:
torch.abs(a - b)

tensor([[0.2281, 0.5256, 0.0807],
        [0.3281, 0.1858, 0.5118]])